@startuml
 :User: as user        #tan
user<-right->(Project Info)
user<-up->(Architecture)
user<-left->(Operational Profile)
user<-down->(Component Selection)
user<-up->(Cost and Sizing)
user<-up->(Simulate)
user<-down->(Results)
user<-down->(Performance)
user<-down->(Optimize)
@enduml